apiVersion: v2
name: h4kstream
description: Music streaming platform with web-based control, live streaming, and WebRTC audio
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - music
  - streaming
  - radio
  - webrtc
  - liquidsoap
home: https://github.com/h4ks-com/h4kstream
maintainers:
  - name: matheusfillipe
sources:
  - https://github.com/h4ks-com/h4kstream
