services:
  main:
    image: python:3.12-slim
    container_name: main
    build:
      context: ./backend
    volumes:
    - ./data:/app/data
    - ${VOLUME_PATH}/music:/music
    - ${VOLUME_PATH}/songs:/songs
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - ICECAST_HOST=icecast
    - MPD_HOST=mpd
    - MPD_PORT=6600
    - VOLUME_PATH=./backend/volumes
    - ADMIN_API_TOKEN=${ADMIN_API_TOKEN}
    - JWT_SECRET=${JWT_SECRET}
    - DEBUG=${DEBUG}
    - RELOAD=${RELOAD}
    depends_on:
    - redis
    - icecast
    - mpd
    ports:
    - '8383:8000'

  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - '6379:6379'

  mpd:
    image: gists/mpd:latest
    container_name: mpd
    user: root
    environment:
    - VOLUME_PATH=./backend/volumes
    volumes:
    - ${VOLUME_PATH}/music:/music
    - ${VOLUME_PATH}/playlist:/var/lib/mpd/playlists:rw
    ports:
    - '6600:6600'
    - '8000:8000'

  icecast:
    image: infiniteproject/icecast:latest
    container_name: icecast
    environment:
    - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
    - ICECAST_PASSWORD=${ICECAST_PASSWORD}
    - ICECAST_HOSTNAME=localhost
    ports:
    - '8005:8000'

  caddy:
    image: caddy:alpine
    container_name: caddy
    # volumes:
    # - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
    - '80:80'

networks:
  default:
    driver: bridge
