services:
  main:
    image: python:3.12-slim
    container_name: main
    build:
      context: ./backend
    volumes:
    - ./backend/app:/app/app
    - ./data:/app/data
    - ${VOLUME_PATH}/music:/music
    - ${VOLUME_PATH}/songs:/songs
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - ICECAST_HOST=icecast
    - MPD_USER_HOST=mpd-user
    - MPD_USER_PORT=6600
    - MPD_FALLBACK_HOST=mpd-fallback
    - MPD_FALLBACK_PORT=6601
    - VOLUME_PATH=./backend/volumes
    - ADMIN_API_TOKEN=${ADMIN_API_TOKEN}
    - LIQUIDSOAP_TOKEN=${LIQUIDSOAP_TOKEN}
    - JWT_SECRET=${JWT_SECRET}
    - LOG_LEVEL=${LOG_LEVEL:-INFO}
    - DEBUG=${DEBUG}
    - RELOAD=${RELOAD}
    depends_on:
    - redis
    - icecast
    - mpd-user
    - mpd-fallback
    ports:
    - '8383:8000'

  redis:
    image: redis:alpine
    container_name: redis
    command:
    - redis-server
    - --save
    - '60'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '900'
    - '1000'
    - --appendonly
    - 'yes'
    - --appendfsync
    - everysec
    volumes:
    - ./data/redis:/data
    ports:
    - '6379:6379'

  mpd-user:
    image: gists/mpd:latest
    container_name: mpd-user
    user: root
    volumes:
    - ${VOLUME_PATH}/music:/music
    - ${VOLUME_PATH}/playlist:/var/lib/mpd/playlists:rw
    - ./mpd/mpd.conf:/etc/mpd.conf:ro
    ports:
    - '6600:6600'
    - '8001:8001'

  mpd-fallback:
    image: gists/mpd:latest
    container_name: mpd-fallback
    user: root
    volumes:
    - ${VOLUME_PATH}/music:/music
    - ${VOLUME_PATH}/playlist-fallback:/var/lib/mpd/playlists:rw
    - ./mpd/mpd-fallback.conf:/etc/mpd.conf:ro
    ports:
    - '6601:6601'
    - '8002:8002'

  liquidsoap:
    image: savonet/liquidsoap:v2.3.0
    container_name: liquidsoap
    volumes:
    - ./liquidsoap/radio.liq:/etc/liquidsoap/radio.liq:ro
    environment:
    - ICECAST_HOST=icecast
    - ICECAST_PORT=8000
    - ICECAST_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    - MPD_USER_HOST=mpd-user
    - MPD_USER_PORT=8001
    - MPD_FALLBACK_HOST=mpd-fallback
    - MPD_FALLBACK_PORT=8002
    - BACKEND_HOST=main
    - BACKEND_PORT=8000
    - LIQUIDSOAP_TOKEN=${LIQUIDSOAP_TOKEN}
    depends_on:
    - mpd-user
    - mpd-fallback
    - icecast
    - main
    restart: unless-stopped
    command: /etc/liquidsoap/radio.liq
    ports:
    - '8003:8003'
    - '1234:1234'

  icecast:
    image: infiniteproject/icecast:latest
    container_name: icecast
    volumes:
    - ./icecast/icecast.xml:/etc/icecast.xml:ro
    environment:
    - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}
    - ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}
    - ICECAST_PASSWORD=${ICECAST_PASSWORD}
    - ICECAST_HOSTNAME=localhost
    ports:
    - '8005:8000'

  caddy:
    image: caddy:alpine
    container_name: caddy
    # volumes:
    # - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
    - '80:80'

networks:
  default:
    driver: bridge
