#+title: Todo

https://chatgpt.com/c/67436428-aff0-8003-a47a-d006df6bdc40

- [X] make yt_dlpt endpoint work with FileUpload or youtube url. Define a default playlist.json list of urls
- [x] setup mdp streaming to icecast and calling the API on startup to set the ~playlist.json~   https://hub.docker.com/r/gists/mpd/tags
- [x] liquidsoap listens to mdp and outputs to iceast 
- [x] Implement the other endpoints with rate limit using redis. We probably limit the user queue to 3 songs
- [x] live user: https://www.liquidsoap.info/doc-2.2.5/harbor.html
- [x] Pause user queue on live stream start and resume on end... tricky
- [x] Trim silence from audio files
- [x] Archive and list shows from disk
- [x] Implement an IRC bot binding when MPD changes or stream the bot echoes to the channel (webhooks?, subscription)
- [x] Webhooks subscription time to live? So they cleanup after some time?
- [x] Check if for user mdp queues there is a limit in the endpoints for upload, limit to 30 min songs, dont even donwload nad just fail otherwise. for amins uploads there should be no limit. If file also make it possible to reject and also have a size limit. Also dont allow addign something already in playlist (next 5 or so?)
- [ ] Transitions in liquidsoap between live and user queue. Should be configurable and pick randomly from multiple for each transition type: https://pixabay.com/sound-effects/search/radio/ should be configurable and in a volume with named known paths.
- [ ] Implement frontend [0/4]
  - [ ] Show current playlist
  - [ ] Show current stream info (live/user)
  - [ ] Show past shows under /archive search open each show
  - [ ] Basic login and user hashed pws in db simple backend. (generate signin url)
  - [ ] File upload
  - [ ] Youtube url
  - [ ] Youtube search
  - [ ] Start custom stream (microphone)
  - [ ] Get key for streaming manually
  - [ ] https://strudel.cc/workshop/getting-started/

- [ ] Route everything over caddy. Load balancer based on request processing blocked. Multiple backends.
- [ ] Keep internal EPs internal only
- [ ] Helm chart?
