files: ^backend/
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Sort imports.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    - id: mypy
      files: ^backend/(app|tests)/.*\.py$
      additional_dependencies: 
        - "types-redis==4.6.0"
      args: [--ignore-missing-imports]

  - repo: https://github.com/myint/docformatter
    rev: "eb1df347edd128b30cd3368dddc3aa65edcfac38"
    hooks:
    - id: docformatter
      args: ["--config", "./backend/pyproject.toml"]
      additional_dependencies: ['.[tomli]']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
