/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiClient } from './ApiClient'

export { ApiError } from './core/ApiError'
export { BaseHttpRequest } from './core/BaseHttpRequest'
export { CancelablePromise, CancelError } from './core/CancelablePromise'
export { OpenAPI } from './core/OpenAPI'
export type { OpenAPIConfig } from './core/OpenAPI'

export type { Body_add_song_queue_add_post } from './models/Body_add_song_queue_add_post'
export type { Body_admin_add_song_admin_queue_add_post } from './models/Body_admin_add_song_admin_queue_add_post'
export type { ErrorResponse } from './models/ErrorResponse'
export type { HTTPValidationError } from './models/HTTPValidationError'
export type { LivestreamTokenCreateRequest } from './models/LivestreamTokenCreateRequest'
export type { LivestreamTokenResponse } from './models/LivestreamTokenResponse'
export type { NowPlayingMetadata } from './models/NowPlayingMetadata'
export type { NowPlayingResponse } from './models/NowPlayingResponse'
export type { RecordingMetadata } from './models/RecordingMetadata'
export type { RecordingsListResponse } from './models/RecordingsListResponse'
export type { ShowRecordings } from './models/ShowRecordings'
export type { SongAddedResponse } from './models/SongAddedResponse'
export type { SongItem } from './models/SongItem'
export type { SuccessResponse } from './models/SuccessResponse'
export type { TokenCreateRequest } from './models/TokenCreateRequest'
export type { TokenCreateResponse } from './models/TokenCreateResponse'
export type { ValidationError } from './models/ValidationError'
export type { WebhookDelivery } from './models/WebhookDelivery'
export type { WebhookStats } from './models/WebhookStats'
export type { WebhookSubscription } from './models/WebhookSubscription'
export type { WebhookSubscriptionRequest } from './models/WebhookSubscriptionRequest'
export type { WebhookSubscriptionResponse } from './models/WebhookSubscriptionResponse'

export { AdminService } from './services/AdminService'
export { DefaultService } from './services/DefaultService'
export { MetadataService } from './services/MetadataService'
export { QueueService } from './services/QueueService'
export { RecordingsService } from './services/RecordingsService'
export { WebhooksService } from './services/WebhooksService'
