{{- if or .Values.mpdUser.enabled .Values.mpdFallback.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h4kstream.fullname" . }}-mpd
  labels:
    {{- include "h4kstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: mpd
data:
  mpd.conf: |
{{ .Files.Get "configs/mpd/mpd.conf" | indent 4 }}
  mpd-fallback.conf: |
{{ .Files.Get "configs/mpd/mpd-fallback.conf" | indent 4 }}
{{- end }}
