{{- if .Values.janus.enabled }}
{{- if not .Values.janus.useDaemonSet }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "h4kstream.fullname" . }}-janus
  labels:
    {{- include "h4kstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: janus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "h4kstream.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: janus
  template:
    metadata:
      labels:
        {{- include "h4kstream.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: janus
    spec:
      {{- if .Values.janus.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: janus
          image: "{{ .Values.janus.image.repository }}:{{ .Values.janus.image.tag }}"
          imagePullPolicy: {{ .Values.janus.image.pullPolicy }}
          command: ["/usr/local/bin/janus"]
          args: ["--configs-folder=/usr/local/etc/janus"]
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
            - name: admin
              containerPort: 8089
              protocol: TCP
          volumeMounts:
            - name: config-janus
              mountPath: /usr/local/etc/janus/janus.jcfg
              subPath: janus.jcfg
            - name: config-streaming
              mountPath: /usr/local/etc/janus/janus.plugin.streaming.jcfg
              subPath: janus.plugin.streaming.jcfg
          resources:
            {{- toYaml .Values.janus.resources | nindent 12 }}
      volumes:
        - name: config-janus
          configMap:
            name: {{ include "h4kstream.fullname" . }}-janus
        - name: config-streaming
          configMap:
            name: {{ include "h4kstream.fullname" . }}-janus
{{- end }}
{{- end }}
