{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "h4kstream.fullname" . }}-strip-stream-prefix
  labels:
    {{- include "h4kstream.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /stream
    forceSlash: false
{{- end }}
