{{- if and .Values.persistence.recordings.enabled .Values.persistence.recordings.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "h4kstream.fullname" . }}-recordings
  labels:
    {{- include "h4kstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.persistence.recordings.accessMode }}
  {{- if .Values.persistence.recordings.storageClass }}
  storageClassName: {{ .Values.persistence.recordings.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.recordings.size }}
{{- end }}
