apiVersion: v1
kind: Secret
metadata:
  name: {{ include "h4kstream.fullname" . }}-secrets
  labels:
    {{- include "h4kstream.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_API_TOKEN: {{ .Values.backend.secrets.ADMIN_API_TOKEN | quote }}
  LIQUIDSOAP_TOKEN: {{ .Values.backend.secrets.LIQUIDSOAP_TOKEN | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | quote }}
  LOGTO_ENDPOINT: {{ .Values.backend.secrets.LOGTO_ENDPOINT | quote }}
  LOGTO_APP_ID: {{ .Values.backend.secrets.LOGTO_APP_ID | quote }}
  LOGTO_APP_SECRET: {{ .Values.backend.secrets.LOGTO_APP_SECRET | quote }}
  LOGTO_REDIRECT_URI: {{ .Values.backend.secrets.LOGTO_REDIRECT_URI | quote }}
  NAVIDROME_USER: {{ .Values.backend.secrets.NAVIDROME_USER | quote }}
  NAVIDROME_PASSWORD: {{ .Values.backend.secrets.NAVIDROME_PASSWORD | quote }}
