{{- if .Values.mpdUser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "h4kstream.fullname" . }}-mpd-user
  labels:
    {{- include "h4kstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: mpd-user
spec:
  type: ClusterIP
  ports:
    - port: 6600
      targetPort: mpd
      protocol: TCP
      name: mpd
    - port: 8001  # Expose MPD HTTP stream (from mpd.conf port 8001)
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "h4kstream.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mpd-user
{{- end }}
