repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.1
  hooks:
  - id: ruff
    args: ["--fix"]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes, --line-width, "120"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    files: ^e2e/tests/.*\.py$
    additional_dependencies:
    - "httpx==0.28.1"
    - "python-dotenv==1.1.1"
    - "pytest>=8.4.2"
    - "redis>=5.2.1"
    - "types-redis>=4.6.0.20241004"
    - "pyjwt>=2.10.0"
    args:
    - --disable-error-code=attr-defined

- repo: local
  hooks:
  - id: no-scoped-imports
    name: No scoped imports (must be at top of file)
    entry: bash -c 'if grep -rn "^[[:space:]].*\bimport\b" e2e/tests --include="*.py" | grep -v "^[^:]*:[[:space:]]*#"; then
      echo "❌ Found scoped imports - all imports must be at top of file"; exit 1; fi'
    language: system
    files: ^e2e/.*\.py$
    pass_filenames: false
