{{- if and .Values.persistence.music.enabled .Values.persistence.music.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hackstream.fullname" . }}-music
  labels:
    {{- include "hackstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.persistence.music.accessMode }}
  {{- if .Values.persistence.music.storageClass }}
  storageClassName: {{ .Values.persistence.music.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.music.size }}
{{- end }}
