{{- if .Values.janus.enabled }}
{{- if not .Values.janus.hostNetwork }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackstream.fullname" . }}-janus
  labels:
    {{- include "hackstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: janus
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
    - port: 8089
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "hackstream.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: janus
{{- end }}
{{- end }}
