name: Build and Push Docker Images

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      image_name: h4kstream-backend
      context: ./backend
      dockerfile: ./backend/Dockerfile
      docker_hub_username: mattfly
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  build-frontend:
    name: Build Frontend
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      image_name: h4kstream-frontend
      context: .
      dockerfile: ./frontend/Dockerfile
      docker_hub_username: mattfly
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
